/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import ClassesConsulta.Veiculo;
import DAO.ConexaoBanco;
import DAO.VeiculoTerceirizadoDAO;
import Tabelas.VeiculoTableModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author PPW
 */
public class TelaCadastroVeiculoTerceirizado extends javax.swing.JFrame {
    private TelaPrincipal telaAnterior;
    private VeiculoTableModel model;
    private Veiculo veiculo;
    private String veiculoo;
    private String carreta;
    
    public String getVeiculoo() {
        return veiculoo;
    }

    public void setVeiculoo(String veiculoo) {
        this.veiculoo = veiculoo;
    }

    public String getCarreta() {
        return carreta;
    }

    public void setCarreta(String carreta) {
        this.carreta = carreta;
    }
    
    
    /**
     * Creates new form TelaCadastroVeiculoProprio
     */
    public TelaCadastroVeiculoTerceirizado() {
        initComponents();
    }
    
    public TelaCadastroVeiculoTerceirizado(TelaPrincipal telaAnterior) {
        this();
        this.telaAnterior = telaAnterior;
        
        VeiculoTableModel v = new VeiculoTableModel();
        model = new VeiculoTableModel(v.ConsultaVeiculoTerceirizado());
        jt_cadastro_cliente.setModel(model);
                  
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        tf_placacavalo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tf_cod = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tf_marca = new javax.swing.JTextField();
        cb_veiculo_veiculo_terceirizado = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cb_carreta_veiculo_terceirizado = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        tf_modelo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_cor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_placacarreta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_ano = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        tf_proprietario = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btn_salvar_veiculo_terceirizado = new javax.swing.JButton();
        btn_alterar_veiculo_terceirizado = new javax.swing.JButton();
        btn_limpar_veiculo_terceirizado = new javax.swing.JButton();
        btn_excluir_veiculo_terceirizado1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_cadastro_cliente = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CADASTRO VEÍCULO TERCEIRIZADO");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("MARCA:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("PLACA/CAVALO MECÂNICO:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("CÓDIGO/MOTORISTA:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("VEÍCULO:");

        cb_veiculo_veiculo_terceirizado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_veiculo_veiculo_terceirizado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CAMINHÂO VUC", "CAMINHÂO TOCO", "CAMINHÂO TRUCK", "CAVALO MECÂNICO", "CAVALO MEÂNICO TRUCADO" }));
        cb_veiculo_veiculo_terceirizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_veiculo_veiculo_terceirizadoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("CARRETA:");

        cb_carreta_veiculo_terceirizado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_carreta_veiculo_terceirizado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NÂO", "CARRETA 2 EIXOS", "CARRETA 3 EIXOS", "CARRETA CAVALO TRUCADO", "BITREM" }));
        cb_carreta_veiculo_terceirizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_carreta_veiculo_terceirizadoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("MODELO:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("COR:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("PLACA/CARRETA:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("ANO:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("PROPRIETÁRIO:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_placacavalo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_placacarreta, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_ano))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_veiculo_veiculo_terceirizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_carreta_veiculo_terceirizado, 0, 1, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_cor, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_proprietario)))
                .addContainerGap())
            .addComponent(jSeparator2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(cb_veiculo_veiculo_terceirizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cb_carreta_veiculo_terceirizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(tf_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tf_cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_placacavalo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tf_placacarreta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tf_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_proprietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_salvar_veiculo_terceirizado.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_salvar_veiculo_terceirizado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/download.png"))); // NOI18N
        btn_salvar_veiculo_terceirizado.setText("SALVAR");
        btn_salvar_veiculo_terceirizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvar_veiculo_terceirizadoActionPerformed(evt);
            }
        });

        btn_alterar_veiculo_terceirizado.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_alterar_veiculo_terceirizado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/under-construction.png"))); // NOI18N
        btn_alterar_veiculo_terceirizado.setText("ALTERAR");
        btn_alterar_veiculo_terceirizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterar_veiculo_terceirizadoActionPerformed(evt);
            }
        });

        btn_limpar_veiculo_terceirizado.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_limpar_veiculo_terceirizado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Write Document.png"))); // NOI18N
        btn_limpar_veiculo_terceirizado.setText("LIMPAR");
        btn_limpar_veiculo_terceirizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpar_veiculo_terceirizadoActionPerformed(evt);
            }
        });

        btn_excluir_veiculo_terceirizado1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_excluir_veiculo_terceirizado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Mr. Bomb.png"))); // NOI18N
        btn_excluir_veiculo_terceirizado1.setText("EXCLUIR");
        btn_excluir_veiculo_terceirizado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluir_veiculo_terceirizado1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btn_salvar_veiculo_terceirizado)
                .addGap(71, 71, 71)
                .addComponent(btn_alterar_veiculo_terceirizado)
                .addGap(61, 61, 61)
                .addComponent(btn_excluir_veiculo_terceirizado1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btn_limpar_veiculo_terceirizado)
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_alterar_veiculo_terceirizado, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_salvar_veiculo_terceirizado, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_limpar_veiculo_terceirizado, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_excluir_veiculo_terceirizado1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jt_cadastro_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jt_cadastro_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_cadastro_clienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_cadastro_cliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-844)/2, (screenSize.height-605)/2, 844, 605);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salvar_veiculo_terceirizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvar_veiculo_terceirizadoActionPerformed
        Integer cod  = Integer.parseInt(tf_cod.getText());
        String Marca = tf_marca.getText();
        String modelo = tf_modelo.getText();
        String Cor = tf_cor.getText();
        String Placacavalo = tf_placacavalo.getText();
        String Placacarreta = tf_placacarreta.getText();
        String ano  = tf_ano.getText();
        String nome = tf_proprietario.getText();
        
        veiculo = new Veiculo(nome, cod, Marca, modelo, Placacavalo, Placacarreta, ano, Cor, veiculoo, carreta);
        
        VeiculoTerceirizadoDAO inserir = new VeiculoTerceirizadoDAO();
        inserir.inserirVeiculoTerceirizado(veiculo);
        
        VeiculoTableModel obj = new VeiculoTableModel();
        model = new VeiculoTableModel(obj.ConsultaVeiculoTerceirizado());
        jt_cadastro_cliente.setModel(model);

    }//GEN-LAST:event_btn_salvar_veiculo_terceirizadoActionPerformed

    private void btn_alterar_veiculo_terceirizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterar_veiculo_terceirizadoActionPerformed
        Integer cod  = Integer.parseInt(tf_cod.getText());
        String Marca = tf_marca.getText();
        String modelo = tf_modelo.getText();
        String Cor = tf_cor.getText();
        String Placacavalo = tf_placacavalo.getText();
        String Placacarreta = tf_placacarreta.getText();
        String ano  = tf_ano.getText();
        String nome = tf_proprietario.getText();
        
        veiculo = new Veiculo(nome, cod, Marca, modelo, Placacavalo, Placacarreta, ano, Cor, veiculoo, carreta);
       
        
        if(jt_cadastro_cliente.getSelectedRowCount() > 0){
            VeiculoTerceirizadoDAO atualizar = new VeiculoTerceirizadoDAO();
            atualizar.updateVeiculoTerceirizado(veiculo);
        }else{
            JOptionPane.showMessageDialog(null, "ESCOLHA UM REGISTRO PARA SER ALTERADO");
        }
        
        VeiculoTableModel v1 = new VeiculoTableModel();
        model = new VeiculoTableModel(v1.ConsultaVeiculoTerceirizado());
        jt_cadastro_cliente.setModel(model);
        
    }//GEN-LAST:event_btn_alterar_veiculo_terceirizadoActionPerformed

    private void btn_limpar_veiculo_terceirizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpar_veiculo_terceirizadoActionPerformed
        tf_cod.setText("");
        tf_marca.setText("");
        tf_modelo.setText("");
        tf_cor.setText("");
        tf_placacavalo.setText("");
        tf_placacarreta.setText("");
        tf_ano.setText("");
        tf_proprietario.setText("");
    }//GEN-LAST:event_btn_limpar_veiculo_terceirizadoActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        telaAnterior.setEnabled(true);
    }//GEN-LAST:event_formWindowClosed

    private void cb_veiculo_veiculo_terceirizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_veiculo_veiculo_terceirizadoActionPerformed
        String opcao[] = {"CAMINHÂO VUC", "CAMINHÂO TOCO", "CAMINHÂO TRUCK", "CAVALO MECÂNICO", "CAVALO MEÂNICO TRUCADO"};

        String escolha[] = {"CAMINHÂO VUC", "CAMINHÂO TOCO", "CAMINHÂO TRUCK", "CAVALO MECÂNICO", "CAVALO MEÂNICO TRUCADO"};
        
        Veiculo v = new Veiculo();
        for (int i = 0; i < opcao.length; i++) {
            if (cb_veiculo_veiculo_terceirizado.getSelectedItem().equals(opcao[i])) {
                setVeiculoo((escolha[i]));
            }
        }
    }//GEN-LAST:event_cb_veiculo_veiculo_terceirizadoActionPerformed

    private void cb_carreta_veiculo_terceirizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_carreta_veiculo_terceirizadoActionPerformed
        String opcao[] = {"NÂO", "CARRETA 2 EIXOS", "CARRETA 3 EIXOS", "CARRETA CAVALO TRUCADO", "BITREM"};

        String escolha[] = {"NÂO", "CARRETA 2 EIXOS", "CARRETA 3 EIXOS", "CARRETA CAVALO TRUCADO", "BITREM"};
        
        for (int i = 0; i < opcao.length; i++) {
            if (cb_carreta_veiculo_terceirizado.getSelectedItem().equals(opcao[i])) {
               setCarreta((escolha[i]));
            }
        }
        
    }//GEN-LAST:event_cb_carreta_veiculo_terceirizadoActionPerformed

    private void jt_cadastro_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_cadastro_clienteMouseClicked
        VeiculoTerceirizadoDAO.cod = (Integer) jt_cadastro_cliente.getValueAt(jt_cadastro_cliente.getSelectedRow(), 0);
        
        Connection conn = new ConexaoBanco().conectaAgora();
        if (conn != null){
            try{
                Statement estado = conn.createStatement();
                Statement estado1 = conn.createStatement();
                ResultSet rs = estado.executeQuery("SELECT cod_motorista, marca, modelo, cor, placacavalo, placacarreta, ano FROM veiculo_motorista_terceirizado WHERE cod_motorista = " + VeiculoTerceirizadoDAO.cod + " ");
                ResultSet rs1 = estado1.executeQuery("SELECT nome FROM motorista_terceirizado WHERE cod = " + VeiculoTerceirizadoDAO.cod + " ");      
                while(rs.next() && rs1.next()){
                    tf_cod.setText(rs.getString("cod_motorista"));
                    tf_marca.setText(rs.getString("marca"));
                    tf_modelo.setText(rs.getString("modelo"));
                    tf_cor.setText(rs.getString("cor"));
                    tf_placacavalo.setText(rs.getString("placacavalo"));
                    tf_placacarreta.setText(rs.getString("placacarreta"));
                    tf_ano.setText(rs.getString("ano"));
                    tf_proprietario.setText(rs1.getString("nome"));
                }
                rs.close();
                rs1.close();
                
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex);
            }      
        }
    }//GEN-LAST:event_jt_cadastro_clienteMouseClicked

    private void btn_excluir_veiculo_terceirizado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluir_veiculo_terceirizado1ActionPerformed
        Connection conn = new ConexaoBanco().conectaAgora();
        int x = jt_cadastro_cliente.getSelectedRow();  
        VeiculoTerceirizadoDAO.cod = (Integer) jt_cadastro_cliente.getValueAt(x, 0);
        
        
        if (jt_cadastro_cliente.getSelectedRowCount() > 0) {
            try {
                VeiculoTerceirizadoDAO deletar = new VeiculoTerceirizadoDAO(); 
                deletar.deletarRegistro(); 
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "O REGISTRO NÂO FOI EXCLUÍDO COM SUCESSO!");
        }
        
        VeiculoTableModel obj = new VeiculoTableModel();
        model = new VeiculoTableModel(obj.ConsultaVeiculoTerceirizado());
        jt_cadastro_cliente.setModel(model);
    }//GEN-LAST:event_btn_excluir_veiculo_terceirizado1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVeiculoTerceirizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVeiculoTerceirizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVeiculoTerceirizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVeiculoTerceirizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroVeiculoTerceirizado().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alterar_veiculo_terceirizado;
    private javax.swing.JButton btn_excluir_veiculo_terceirizado1;
    private javax.swing.JButton btn_limpar_veiculo_terceirizado;
    private javax.swing.JButton btn_salvar_veiculo_terceirizado;
    private javax.swing.JComboBox cb_carreta_veiculo_terceirizado;
    private javax.swing.JComboBox cb_veiculo_veiculo_terceirizado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jt_cadastro_cliente;
    private javax.swing.JTextField tf_ano;
    private javax.swing.JTextField tf_cod;
    private javax.swing.JTextField tf_cor;
    private javax.swing.JTextField tf_marca;
    private javax.swing.JTextField tf_modelo;
    private javax.swing.JTextField tf_placacarreta;
    private javax.swing.JTextField tf_placacavalo;
    private javax.swing.JTextField tf_proprietario;
    // End of variables declaration//GEN-END:variables

}
