/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import SuperClasses.Contato;
import SuperClasses.Endereco;
import SuperClasses.Frete;

/**
 *
 * @author PPW
 */
public class TelaFretePesado extends javax.swing.JFrame {
    private TelaPrincipal telaAnterior;
    private String estado;

    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }
    
    
    
    
    public TelaFretePesado() {
        initComponents();
    }
    
    public TelaFretePesado(TelaPrincipal telaAnterior) {
        this();
        this.telaAnterior = telaAnterior;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Painel_Terceirizado = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        tf_cod_motorista_terceirizado1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_cod_cliente_juridico1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        tf_cep_remetente1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_cep_destinatario1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cb_uf1 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        tf_endereco1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tf_numero1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        tf_comercial1 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        btn_salvar1 = new javax.swing.JButton();
        btn_limpar1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        tf_peso1 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        tf_valorFrete1 = new javax.swing.JTextField();
        tf_residencial1 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        tf_email = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        tf_celular1 = new javax.swing.JTextField();
        tf_bairro2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tf_cidade1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        Painel_Proprio = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CADASTRAR FRETE PESADO");
        setBackground(new java.awt.Color(204, 204, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tf_cod_motorista_terceirizado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cod_motorista_terceirizado1ActionPerformed(evt);
            }
        });
        jPanel5.add(tf_cod_motorista_terceirizado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 13, 150, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("CÓDIGO/Motorista:");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("CÓDIGO/Cliente:");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 13, -1, -1));

        tf_cod_cliente_juridico1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cod_cliente_juridico1ActionPerformed(evt);
            }
        });
        jPanel5.add(tf_cod_cliente_juridico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 13, 150, -1));
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 39, 600, 10));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("CEP - REMETENTE:");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));
        jPanel5.add(tf_cep_remetente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 156, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("CEP - DESTINATÁRIO:");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        tf_cep_destinatario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cep_destinatario1ActionPerformed(evt);
            }
        });
        jPanel5.add(tf_cep_destinatario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 150, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("UF:");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        cb_uf1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cb_uf1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cb_uf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_uf1ActionPerformed(evt);
            }
        });
        jPanel5.add(cb_uf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 84, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("LOGRADOURO:");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));
        jPanel5.add(tf_endereco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 361, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("BAIRRO:");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));
        jPanel5.add(tf_numero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 60, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("NÚMERO:");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, -1, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel39.setText("TELEFONE RESIDENCIAL:");
        jPanel5.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        jPanel5.add(tf_comercial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 130, -1));

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel40.setText("TELEFONE COMERCIAL:");
        jPanel5.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 150, -1));

        jPanel11.setBackground(new java.awt.Color(102, 102, 255));
        jPanel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_salvar1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_salvar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/download.png"))); // NOI18N
        btn_salvar1.setText("SALVAR");
        btn_salvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvar1ActionPerformed(evt);
            }
        });

        btn_limpar1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_limpar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Write Document.png"))); // NOI18N
        btn_limpar1.setText("LIMPAR");
        btn_limpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_salvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_limpar1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_salvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_limpar1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 610, 80));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 44)); // NOI18N
        jLabel2.setText("ENDEREÇO DESTINATÁRIO");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 330, 40));

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel43.setText("PESO:");
        jPanel5.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));
        jPanel5.add(tf_peso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 230, -1));

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel44.setText("VALOR:");
        jPanel5.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 60, -1));

        tf_valorFrete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_valorFrete1ActionPerformed(evt);
            }
        });
        jPanel5.add(tf_valorFrete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 220, -1));
        jPanel5.add(tf_residencial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 130, -1));

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel45.setText("TELEFONE CELULAR:");
        jPanel5.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));
        jPanel5.add(tf_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 220, -1));

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel46.setText("EMAIL:");
        jPanel5.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 60, -1));
        jPanel5.add(tf_celular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 130, -1));
        jPanel5.add(tf_bairro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 160, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("CIDADE:");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));
        jPanel5.add(tf_cidade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 160, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("CLIENTE JURÍDICO", jPanel1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("CLIENTE FISICO", jPanel4);

        javax.swing.GroupLayout Painel_TerceirizadoLayout = new javax.swing.GroupLayout(Painel_Terceirizado);
        Painel_Terceirizado.setLayout(Painel_TerceirizadoLayout);
        Painel_TerceirizadoLayout.setHorizontalGroup(
            Painel_TerceirizadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        Painel_TerceirizadoLayout.setVerticalGroup(
            Painel_TerceirizadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_TerceirizadoLayout.createSequentialGroup()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("FRETE PESADO - MOTORISTA TERCEIRIZADO", Painel_Terceirizado);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("           CLIENTE JURÍDICO                 ", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("                   CLIENTE FÍSICO                                ", jPanel3);

        javax.swing.GroupLayout Painel_ProprioLayout = new javax.swing.GroupLayout(Painel_Proprio);
        Painel_Proprio.setLayout(Painel_ProprioLayout);
        Painel_ProprioLayout.setHorizontalGroup(
            Painel_ProprioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        Painel_ProprioLayout.setVerticalGroup(
            Painel_ProprioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );

        jTabbedPane1.addTab("FRETE PESADO - MOTORISTA PRÓPRIO", Painel_Proprio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-628)/2, (screenSize.height-434)/2, 628, 434);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        telaAnterior.setEnabled(true);
    }//GEN-LAST:event_formWindowClosed

    private void tf_cod_motorista_terceirizado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cod_motorista_terceirizado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_cod_motorista_terceirizado1ActionPerformed

    private void tf_cod_cliente_juridico1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cod_cliente_juridico1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_cod_cliente_juridico1ActionPerformed

    private void cb_uf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_uf1ActionPerformed
        String siglas[] = {"AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS",            "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO"};

        String uf[] = {"Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceara", "Distrito Federal",
            "Espírito Santo", "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais", "Pará",
            "Paraíba", "Paraná", "Pernambuco", "Piauí", "Rio de Janeiro", "Rio Grande do Norte", "Rio Grande do sul",
            "Rondônia", "Roraima", "Santa Catarina", "São Paulo", "Sergipe", "Tocantins"};

        for (int i = 0; i < siglas.length; i++) {
            if (cb_uf1.getSelectedItem().equals(siglas[i])) {
                

            }
        }
    }//GEN-LAST:event_cb_uf1ActionPerformed

    private void btn_salvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvar1ActionPerformed
        Integer codigoMotorista = Integer.parseInt(tf_cod_motorista_terceirizado1.getText());
        Integer codigoJuridico  = Integer.parseInt(tf_cod_cliente_juridico1.getText());
        String cepRemetente     = tf_cep_remetente1.getText();
        String cepDestinatario  = tf_cep_destinatario1.getText();
        String logradouro       = tf_endereco1.getText();
        String bairro           = tf_numero1.getText();
        String cidade           = tf_cidade1.getText();
        String numero           = tf_numero1.getText();
        String residencial      = tf_residencial1.getText();
        String comercial        = tf_comercial1.getText();
        String celular          = tf_celular1.getText();
        String email            = tf_email.getText();
        String peso             = tf_comercial1.getText();
        Double valor            = Double.parseDouble(tf_valorFrete1.getText());
        
        Contato contato = new Contato(residencial, celular, email, comercial);
        Endereco endereco = new Endereco(logradouro, numero, cidade, bairro, cepDestinatario, estado);
        Frete frete = new Frete(codigoMotorista, codigoJuridico, cepRemetente, cepDestinatario, endereco, contato, peso, valor);
        
        
        

    }//GEN-LAST:event_btn_salvar1ActionPerformed

    private void btn_limpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpar1ActionPerformed
        tf_cod_motorista_terceirizado1.setText("");
        tf_cod_cliente_juridico1.setText("");
        tf_cep_remetente1.setText("");
        tf_cep_destinatario1.setText("");
        tf_endereco1.setText("");
        tf_numero1.setText("");
        tf_cidade1.setText("");
        tf_residencial1.setText("");
        tf_comercial1.setText("");
        tf_celular1.setText("");
        tf_email.setText("");
        tf_comercial1.setText("");
        tf_valorFrete1.setText("");
        
    }//GEN-LAST:event_btn_limpar1ActionPerformed

    private void tf_cep_destinatario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cep_destinatario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_cep_destinatario1ActionPerformed

    private void tf_valorFrete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_valorFrete1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_valorFrete1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFretePesado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFretePesado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFretePesado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFretePesado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFretePesado().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Painel_Proprio;
    private javax.swing.JPanel Painel_Terceirizado;
    private javax.swing.JButton btn_limpar1;
    private javax.swing.JButton btn_salvar1;
    private javax.swing.JComboBox cb_uf1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField tf_bairro2;
    private javax.swing.JTextField tf_celular1;
    private javax.swing.JTextField tf_cep_destinatario1;
    private javax.swing.JTextField tf_cep_remetente1;
    private javax.swing.JTextField tf_cidade1;
    private javax.swing.JTextField tf_cod_cliente_juridico1;
    private javax.swing.JTextField tf_cod_motorista_terceirizado1;
    private javax.swing.JTextField tf_comercial1;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_endereco1;
    private javax.swing.JTextField tf_numero1;
    private javax.swing.JTextField tf_peso1;
    private javax.swing.JTextField tf_residencial1;
    private javax.swing.JTextField tf_valorFrete1;
    // End of variables declaration//GEN-END:variables
}
