/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import DAO.ConexaoBanco;
import DAO.MotoristaTerceirizadoDAO;
import SuperClasses.Contato;
import SuperClasses.Endereco;
import SuperClasses.Motorista;
import Tabelas.MotoristaTableModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author PPW
 */
public class TelaCadastroMotoristaTerceirizado extends javax.swing.JFrame {
    private TelaPrincipal telaAnterior;   
    private MotoristaTableModel model;
    private Motorista motorista;
    private String sexo;
    private String estado;
    
    
    public String getSexo() {
        return sexo;
    }

    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }
    

    
    
    
    /**
     * Creates new form TelaCadastroMotoristaTerceirizado
     */
    public TelaCadastroMotoristaTerceirizado() {
        super();
        initComponents();
        setResizable(false);

    }
   
    public TelaCadastroMotoristaTerceirizado(TelaPrincipal telaAnterior) {
        this();
        this.telaAnterior = telaAnterior;
        
        MotoristaTableModel obj = new MotoristaTableModel();
        model = new MotoristaTableModel(obj.ConsultaBancoTerceirizado());
        jT_tela_cadastro_motorista_terceirizado.setModel(model);     
    }
    
    //mostra o JDialog de Alterar o motorista Terceirizado
    

     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Nome = new javax.swing.JLabel();
        tf_nome = new javax.swing.JTextField();
        CPF = new javax.swing.JLabel();
        tf_cpf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_rntcr = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_cnh = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_inss = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        cb_uf_motorista_terceirizado = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        tf_endereco = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_numero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_cidade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_bairro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        tf_cep = new javax.swing.JTextField();
        cb_sexo_motorista_terceirizado = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        tf_rg = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tf_residencial = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tf_celular = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tf_email = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btn_salvar_motorista_terceirizado = new javax.swing.JButton();
        btn_alterar = new javax.swing.JButton();
        btn_excluir_motorista_terceirizado = new javax.swing.JButton();
        btn_limpar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jT_tela_cadastro_motorista_terceirizado = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CADASTRO DE MOTORISTA TERCEIRIZADO");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Nome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Nome.setText("NOME:");

        tf_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nomeActionPerformed(evt);
            }
        });

        CPF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CPF.setText("CPF");

        tf_cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cpfActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("RG:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("RNTCR:");

        tf_rntcr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_rntcrActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("CNH:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Inscr. INSS Nº:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("UF:");

        cb_uf_motorista_terceirizado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cb_uf_motorista_terceirizado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cb_uf_motorista_terceirizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_uf_motorista_terceirizadoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("ENDEREÇO/RUA:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("NÚMERO:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("CIDADE:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("BAIRRO:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("CEP:");

        cb_sexo_motorista_terceirizado.setMaximumRowCount(2);
        cb_sexo_motorista_terceirizado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M", "F" }));
        cb_sexo_motorista_terceirizado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cb_sexo_motorista_terceirizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_sexo_motorista_terceirizadoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("SEXO:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("TELEFONE RESIDENCIAL:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("TELEFONE(CELULAR):");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("E-MAIL:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_endereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_uf_motorista_terceirizado, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_rg, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_sexo_motorista_terceirizado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_rntcr, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_cnh, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_inss))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_cep))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_residencial, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_celular, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_email)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome)
                    .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CPF)
                    .addComponent(tf_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cb_sexo_motorista_terceirizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(tf_rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_rntcr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tf_cnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tf_inss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_uf_motorista_terceirizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(tf_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tf_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(tf_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(tf_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_residencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(tf_celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_salvar_motorista_terceirizado.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_salvar_motorista_terceirizado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/download.png"))); // NOI18N
        btn_salvar_motorista_terceirizado.setText("SALVAR");
        btn_salvar_motorista_terceirizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvar_motorista_terceirizadoActionPerformed(evt);
            }
        });

        btn_alterar.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/under-construction.png"))); // NOI18N
        btn_alterar.setText("ALTERAR");
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });

        btn_excluir_motorista_terceirizado.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_excluir_motorista_terceirizado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Mr. Bomb.png"))); // NOI18N
        btn_excluir_motorista_terceirizado.setText("EXCLUIR");
        btn_excluir_motorista_terceirizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluir_motorista_terceirizadoActionPerformed(evt);
            }
        });

        btn_limpar.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_limpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Write Document.png"))); // NOI18N
        btn_limpar.setText("LIMPAR");
        btn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btn_salvar_motorista_terceirizado)
                .addGap(51, 51, 51)
                .addComponent(btn_alterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_excluir_motorista_terceirizado)
                .addGap(58, 58, 58)
                .addComponent(btn_limpar)
                .addGap(44, 44, 44))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_salvar_motorista_terceirizado, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_excluir_motorista_terceirizado, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ultimos.png"))); // NOI18N

        jScrollPane2.setBackground(new java.awt.Color(153, 153, 153));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jT_tela_cadastro_motorista_terceirizado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jT_tela_cadastro_motorista_terceirizado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jT_tela_cadastro_motorista_terceirizadoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jT_tela_cadastro_motorista_terceirizado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabel16)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-863)/2, (screenSize.height-627)/2, 863, 627);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        telaAnterior.setEnabled(true);
    }//GEN-LAST:event_formWindowClosed

    private void tf_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nomeActionPerformed

    private void tf_cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_cpfActionPerformed

    private void tf_rntcrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_rntcrActionPerformed
    }//GEN-LAST:event_tf_rntcrActionPerformed

    private void btn_salvar_motorista_terceirizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvar_motorista_terceirizadoActionPerformed
        String nome          = tf_nome.getText();
        String cpf           = tf_cpf.getText();
        String rg            = tf_rg.getText();
        String cnh           = tf_cnh.getText();
        String inss          = tf_inss.getText();
        String rntcr         = tf_rntcr.getText();
        String logradouro    = tf_endereco.getText();
        String bairro        = tf_bairro.getText();
        String cep           = tf_cep.getText();
        String numero        = tf_numero.getText();
        String email         = tf_email.getText();
        String cidade        = tf_cidade.getText();
        String celular       = tf_celular.getText();
        String residencial   = tf_residencial.getText();
        
        Endereco endereco   = new Endereco (logradouro, numero, cidade, bairro, cep, estado);
        Contato contato     = new Contato  (residencial, celular, email);
        motorista           = new Motorista(inss, rntcr, cnh, endereco, contato, nome, cpf, rg, sexo);
        
        
        MotoristaTerceirizadoDAO inserir = new MotoristaTerceirizadoDAO();
        inserir.inserirMotoristaTerceirizado(motorista);
        
        MotoristaTableModel obj = new MotoristaTableModel();
        model = new MotoristaTableModel(obj.ConsultaBancoTerceirizado());
        jT_tela_cadastro_motorista_terceirizado.setModel(model);
        
        
        
    }//GEN-LAST:event_btn_salvar_motorista_terceirizadoActionPerformed

    private void cb_sexo_motorista_terceirizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_sexo_motorista_terceirizadoActionPerformed
        
        if (cb_sexo_motorista_terceirizado.getSelectedItem().equals("M")) {
            sexo = ("Masculino");

        } else if (cb_sexo_motorista_terceirizado.getSelectedItem().equals("F")) {
            sexo = ("Feminino");
        }
    }//GEN-LAST:event_cb_sexo_motorista_terceirizadoActionPerformed

    private void cb_uf_motorista_terceirizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_uf_motorista_terceirizadoActionPerformed
        String siglas[] = {"AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS",            "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO"};

        String uf[] = {"Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceara", "Distrito Federal",
            "Espírito Santo", "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais", "Pará",
            "Paraíba", "Paraná", "Pernambuco", "Piauí", "Rio de Janeiro", "Rio Grande do Norte", "Rio Grande do sul",
            "Rondônia", "Roraima", "Santa Catarina", "São Paulo", "Sergipe", "Tocantins"};
        
        Endereco obj = new Endereco(null);
        
        for (int i = 0; i < siglas.length; i++) {
            if (cb_uf_motorista_terceirizado.getSelectedItem().equals(siglas[i])) {
                setEstado((uf[i]));

            }
        }
    }//GEN-LAST:event_cb_uf_motorista_terceirizadoActionPerformed

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
        String nome          = tf_nome.getText();
        String cpf           = tf_cpf.getText();
        String rg            = tf_rg.getText();
        String cnh           = tf_cnh.getText();
        String inss          = tf_inss.getText();
        String rntcr         = tf_rntcr.getText();
        String logradouro    = tf_endereco.getText();
        String bairro        = tf_bairro.getText();
        String cep           = tf_cep.getText();
        String numero        = tf_numero.getText();
        String email         = tf_email.getText();
        String cidade        = tf_cidade.getText();
        String celular       = tf_celular.getText();
        String residencial   = tf_residencial.getText();
        
        Endereco endereco   = new Endereco (logradouro, numero, cidade, bairro, cep, estado);
        Contato contato     = new Contato  (residencial, celular, email);
        motorista           = new Motorista(inss, rntcr, cnh, endereco, contato, nome, cpf, rg, sexo); 
        
        if(jT_tela_cadastro_motorista_terceirizado.getSelectedRowCount() > 0){
             MotoristaTerceirizadoDAO atualizar = new MotoristaTerceirizadoDAO();
             atualizar.updateMotoristaTerceirizado(motorista);
        }else{
            JOptionPane.showMessageDialog(null, "ESCOLHA UM REGISTRO PARA SER ALTERADO");
        }      
        //Atualiza a Tabela realizando uma nova consulta
        MotoristaTableModel obj = new MotoristaTableModel();
        model = new MotoristaTableModel(obj.ConsultaBancoTerceirizado());
        jT_tela_cadastro_motorista_terceirizado.setModel(model);
    }//GEN-LAST:event_btn_alterarActionPerformed

    private void btn_excluir_motorista_terceirizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluir_motorista_terceirizadoActionPerformed
        Connection conn = new ConexaoBanco().conectaAgora();
        int x = jT_tela_cadastro_motorista_terceirizado.getSelectedRow();  
        MotoristaTerceirizadoDAO.cod = (Integer) jT_tela_cadastro_motorista_terceirizado.getValueAt(x, 0);
        
        
        if (jT_tela_cadastro_motorista_terceirizado.getSelectedRowCount() > 0) {
            try {
                MotoristaTerceirizadoDAO deletar = new MotoristaTerceirizadoDAO(); 
                deletar.deletarRegistro(); 
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "ESCOLHA UM REGISTRO PARA SER EXCLUÍDO!");
        }
        
        MotoristaTableModel obj = new MotoristaTableModel();
        model = new MotoristaTableModel(obj.ConsultaBancoTerceirizado());
        jT_tela_cadastro_motorista_terceirizado.setModel(model);
    }//GEN-LAST:event_btn_excluir_motorista_terceirizadoActionPerformed

    private void jT_tela_cadastro_motorista_terceirizadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_tela_cadastro_motorista_terceirizadoMouseClicked
        MotoristaTerceirizadoDAO.cod = (Integer) jT_tela_cadastro_motorista_terceirizado.getValueAt(jT_tela_cadastro_motorista_terceirizado.getSelectedRow(), 0);
        
        Connection conn = new ConexaoBanco().conectaAgora();
        if (conn != null){
            try{
                Statement estado1 = conn.createStatement();
                ResultSet rs = estado1.executeQuery("SELECT nome, cpf, rg, cnh, rntcr, inss FROM motorista_terceirizado WHERE cod = " + MotoristaTerceirizadoDAO.cod + " ");     
                Statement estado2 = conn.createStatement();
                ResultSet rs1 = estado2.executeQuery("SELECT endereco, numero, cidade, bairro, cep FROM endereco_motorista_terceirizado WHERE cod_motorista_t = " + MotoristaTerceirizadoDAO.cod +" ");
                Statement estado3 = conn.createStatement();
                ResultSet rs2 = estado3.executeQuery("SELECT telefone_residencial, telefone_celular, email FROM contato_motorista_terceirizado WHERE cod_motorista_terceirizado = " + MotoristaTerceirizadoDAO.cod +" ");
                while(rs.next() && rs1.next() && rs2.next()){
                    tf_nome.setText(rs.getString("nome"));
                    tf_cpf.setText(rs.getString("cpf"));
                    tf_rg.setText(rs.getString("rg"));
                    tf_cnh.setText(rs.getString("cnh"));
                    tf_rntcr.setText(rs.getString("rntcr"));
                    tf_inss.setText(rs.getString("inss"));
                    tf_endereco.setText(rs1.getString("endereco"));
                    tf_numero.setText(rs1.getString("numero"));
                    tf_cidade.setText(rs1.getString("cidade"));
                    tf_bairro.setText(rs1.getString("bairro"));
                    tf_cep.setText(rs1.getString("cep"));
                    tf_residencial.setText(rs2.getString("telefone_residencial"));
                    tf_celular.setText(rs2.getString("telefone_celular"));
                    tf_email.setText(rs2.getString("email"));
                }
                rs.close();
                rs1.close();
                rs2.close();
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex);
            }      
        }
         
    }//GEN-LAST:event_jT_tela_cadastro_motorista_terceirizadoMouseClicked

    private void btn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparActionPerformed
                    tf_nome.setText("");
                    tf_cpf.setText("");
                    tf_rg.setText("");
                    tf_cnh.setText("");
                    tf_rntcr.setText("");
                    tf_inss.setText("");
                    tf_endereco.setText("");
                    tf_numero.setText("");
                    tf_cidade.setText("");
                    tf_bairro.setText("");
                    tf_cep.setText("");
                    tf_residencial.setText("");
                    tf_celular.setText("");
                    tf_email.setText("");
    }//GEN-LAST:event_btn_limparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroMotoristaTerceirizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroMotoristaTerceirizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroMotoristaTerceirizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroMotoristaTerceirizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroMotoristaTerceirizado().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CPF;
    private javax.swing.JLabel Nome;
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_excluir_motorista_terceirizado;
    private javax.swing.JButton btn_limpar;
    private javax.swing.JButton btn_salvar_motorista_terceirizado;
    private javax.swing.JComboBox cb_sexo_motorista_terceirizado;
    private javax.swing.JComboBox cb_uf_motorista_terceirizado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jT_tela_cadastro_motorista_terceirizado;
    private javax.swing.JTextField tf_bairro;
    private javax.swing.JTextField tf_celular;
    private javax.swing.JTextField tf_cep;
    private javax.swing.JTextField tf_cidade;
    private javax.swing.JTextField tf_cnh;
    private javax.swing.JTextField tf_cpf;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_endereco;
    private javax.swing.JTextField tf_inss;
    private javax.swing.JTextField tf_nome;
    private javax.swing.JTextField tf_numero;
    private javax.swing.JTextField tf_residencial;
    private javax.swing.JTextField tf_rg;
    private javax.swing.JTextField tf_rntcr;
    // End of variables declaration//GEN-END:variables


    
}
